# Generated by Django 4.2.4 on 2023-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail_app', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=254)),
                ('email_to', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
