all_users=[
                                 'ashish@arivani.net',
                                 'mohdsaqib12@gmail.com',
                    
                                 'geotab1@arivani.net',
                                 'geotab2@arivani.net',
                                 'geotab3@arivani.net',
                                 'geotab4@arivani.net',
                                 'geotab5@arivani.net',
                                 'geotab6@arivani.net',
                                 'geotab7@arivani.net',
                                 'geotab8@arivani.net',
                                 'geotab9@arivani.net',
                                 'geotab10@arivani.net',
                                 'geotab11@arivani.net',
                                 'geotab12@arivani.net',
                                 'geotab13@arivani.net',
                                 'geotab14@arivani.net',
                                 'geotab15@arivani.net',
                                 'geotab16@arivani.net',
                                 'geotab17@arivani.net',
                                 'geotab18@arivani.net',
                                 'geotab19@arivani.net',
                                 'geotab20@arivani.net',
                                 'geotab21@arivani.net',
                                 'geotab22@arivani.net',
                                 'geotab23@arivani.net',
                                 'geotab24@arivani.net',
                                 'geotab25@arivani.net',
                                 'geotab26@arivani.net',
                                 'geotab27@arivani.net',
                                 'geotab28@arivani.net',
                                 'geotab29@arivani.net',
                                 'geotab30@arivani.net',
                                 'geotab31@arivani.net',
                                 'geotab32@arivani.net',
                                 'geotab33@arivani.net',
                                 'geotab34@arivani.net',
                                 'geotab35@arivani.net',
                                 'geotab36@arivani.net',
                                 'geotab37@arivani.net',
                                 'geotab38@arivani.net',
                                 'geotab39@arivani.net',
                                 'geotab40@arivani.net',
                                 'geotab41@arivani.net',
                                 'geotab42@arivani.net',
                                 'geotab43@arivani.net',
                                 'geotab44@arivani.net',
                                 'geotab45@arivani.net',
                                 'geotab46@arivani.net',
                                 'geotab47@arivani.net',
                                 'geotab48@arivani.net',
                                 'geotab49@arivani.net',
                                 'geotab50@arivani.net',
                                 'geotab51@arivani.net',
                                 'geotab52@arivani.net',
                                 'geotab53@arivani.net',
                                 'geotab54@arivani.net',
                                 'geotab55@arivani.net',
                                 'geotab56@arivani.net',
                                 'geotab57@arivani.net',
                                 'geotab58@arivani.net',
                                 'geotab59@arivani.net',
                                 'geotab60@arivani.net',
                                 'geotab61@arivani.net',
                                 'geotab62@arivani.net',
                                 'geotab63@arivani.net',
                                 'geotab64@arivani.net',
                                 'geotab65@arivani.net',
                                 'geotab66@arivani.net',
                                 'geotab67@arivani.net',
                                 'geotab68@arivani.net',
                                 'geotab69@arivani.net',
                                 'geotab70@arivani.net',
                                 'geotab71@arivani.net',
                                 'geotab72@arivani.net',
                                 'geotab73@arivani.net',
                                 'geotab74@arivani.net',
                                 'geotab75@arivani.net',
                                 'geotab76@arivani.net',
                                 'geotab77@arivani.net',
                                 'geotab78@arivani.net',
                                 'geotab79@arivani.net',
                                 'geotab80@arivani.net',
                                 'geotab81@arivani.net',
                                 'geotab82@arivani.net',
                                 'geotab83@arivani.net',
                                 'geotab84@arivani.net',
                                 'geotab85@arivani.net',
                                 'geotab86@arivani.net',
                                 'geotab87@arivani.net',
                                 'geotab88@arivani.net',
                                 'geotab89@arivani.net',
                                 'geotab90@arivani.net',
                                 'geotab91@arivani.net',
                                 'geotab92@arivani.net',
                                 'geotab93@arivani.net',
                                 'geotab94@arivani.net',
                                 'geotab95@arivani.net',
                                 'geotab96@arivani.net',
                                 'geotab97@arivani.net',
                                 'geotab98@arivani.net',
                                 'geotab99@arivani.net',
                                 'geotab100@arivani.net',
                                 'geotab101@arivani.net',
                                 'geotab102@arivani.net',
                                 'geotab103@arivani.net',
                                 'geotab104@arivani.net',
                                 'geotab105@arivani.net',
                                 'geotab106@arivani.net',
                                 'geotab107@arivani.net',
                                 'geotab108@arivani.net',
                                 'geotab109@arivani.net',
                                 'geotab110@arivani.net',
                                 'geotab111@arivani.net',
                                 'geotab112@arivani.net',
                                 'geotab113@arivani.net',
                                 'geotab114@arivani.net',
                                 'geotab115@arivani.net',
                                 'geotab116@arivani.net',
                                 'geotab117@arivani.net',
                                 'geotab118@arivani.net',
                                 'geotab119@arivani.net',
                                 'geotab120@arivani.net',
                                 'geotab121@arivani.net',
                                 'geotab122@arivani.net',
                                 'geotab123@arivani.net',
                                 'geotab124@arivani.net',
                                 'geotab125@arivani.net',
                                 'geotab126@arivani.net',
                                 'geotab127@arivani.net',
                                 'geotab128@arivani.net',
                                 'geotab129@arivani.net',
                                 'geotab130@arivani.net',
                                 'geotab131@arivani.net',
                                 'geotab132@arivani.net',
                                 'geotab133@arivani.net',
                                 'geotab134@arivani.net',
                                 'geotab135@arivani.net',
                                 'geotab136@arivani.net',
                                 'geotab137@arivani.net',
                                 'geotab138@arivani.net',
                                 'geotab139@arivani.net',
                                 'geotab140@arivani.net',
                                 'geotab141@arivani.net',
                                 'geotab142@arivani.net',
                                 'geotab143@arivani.net',
                                 'geotab144@arivani.net',
                                 'geotab145@arivani.net',
                                 'geotab146@arivani.net',
                                 'geotab147@arivani.net',
                                 'geotab148@arivani.net',
                                 'geotab149@arivani.net',
                                 'geotab150@arivani.net',
                                 'geotab151@arivani.net',
                                 'geotab152@arivani.net',
                                 'geotab153@arivani.net',
                                 'geotab154@arivani.net',
                                 'geotab155@arivani.net',
                                 'geotab156@arivani.net',
                                 'geotab157@arivani.net',
                                 'geotab158@arivani.net',
                                 'geotab159@arivani.net',
                                 'geotab160@arivani.net',
                                 'geotab161@arivani.net',
                                 'geotab162@arivani.net',
                                 'geotab163@arivani.net',
                                 'geotab164@arivani.net',
                                 'geotab165@arivani.net',
                                 'geotab166@arivani.net',
                                 'geotab167@arivani.net',
                                 'geotab168@arivani.net',
                                 'geotab169@arivani.net',
                                 'geotab170@arivani.net',
                                 'geotab171@arivani.net',
                                 'geotab172@arivani.net',
                                 'geotab173@arivani.net',
                                 'geotab174@arivani.net',
                                 'geotab175@arivani.net',
                                 'geotab176@arivani.net',
                                 'geotab177@arivani.net',
                                 'geotab178@arivani.net',
                                 'geotab179@arivani.net',
                                 'geotab180@arivani.net',
                                 'geotab181@arivani.net',
                                 'geotab182@arivani.net',
                                 'geotab183@arivani.net',
                                 'geotab184@arivani.net',
                                 'geotab185@arivani.net',
                                 'geotab186@arivani.net',
                                 'geotab187@arivani.net',
                                 'geotab188@arivani.net',
                                 'geotab189@arivani.net',
                                 'geotab190@arivani.net',
                                 'geotab191@arivani.net',
                                 'geotab192@arivani.net',
                                 'geotab193@arivani.net',
                                 'geotab194@arivani.net',
                                 'geotab195@arivani.net',
                                 'geotab196@arivani.net',
                                 'geotab197@arivani.net',
                                 'geotab198@arivani.net',
                                 'geotab199@arivani.net',
                                 'geotab200@arivani.net'
                             ]


import sqlite3

conn=sqlite3.connect('db.sqlite3')

cursor=conn.cursor()

cursor.execute(''' create table if not exists auth_user(password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined)
               
               ''')

values = [
    
    ('123456',False,user,user,user,user,False,True,'2023-01-01 00:00:00')for user in all_users
    
    # ('123456', False, 'aahish@arivani.net', 'aahish', 'aahish', 'ashish@arivani.net', False, True, '2023-01-01 00:00:00'),
    # ('123456', False, 'geotab1@arivani.net', 'geotab1@arivani.net', 'geotab1@arivani.net', 'geotab1@arivani.net', False, True, '2023-01-01 00:00:00'),
    # ('123456', False, 'geotab2@arivani.net', 'geotab2@arivani.net', 'geotab2@arivani.net','geotab2@arivani.net', False, True, '2023-01-01 00:00:00'),
    # ('123456', False, 'geotab3@arivani.net', 'geotab3@arivani.net', 'geotab3@arivani.net','geotab3@arivani.net', False, True, '2023-01-01 00:00:00'),
    # ('123456', False, 'geotab4@arivani.net', 'geotab4@arivani.net', 'geotab4@arivani.net','geotab5@arivani.net', False, True, '2023-01-01 00:00:00'),
]

sqlite_insert_query ="INSERT OR IGNORE INTO auth_user (password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (?,?,?,?,?,?,?,?,?)"

try:
    
    cursor.executemany(sqlite_insert_query, (values))
    # cursor.execute("INSERT OR IGNORE INTO auth_user (password,is_superuser,username,first_name,last_name,email,is_staff,is_active,date_joined) VALUES (?,?,?,?,?,?,?,?,?)", ('123456', False, 'myusername', 'FirstName', 'LastName', 'email@email.com', False, True, '2023-01-01 00:00:00'))
    conn.commit()

except sqlite3.IntegrityError:
    print("failed to insert.,there might be a duplicate data")
    
